[workspace]
resolver = "2"
members = ["examples/animated", "examples/console-inertial", "examples/console-transition", "examples/follow-cursor", "examples/shape-animation", "glissade", "glissade-macro"]
